SET VERIFY OFF;
SET SERVEROUTPUT ON;
SET LINESIZE 500;

DROP TRIGGER TRIGGER1; 
DROP TRIGGER TRIGGER2; 

CREATE OR REPLACE TRIGGER TRIGGER1 
BEFORE INSERT 
ON History
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Site Table Before Insert Trigger');
END;
/

CREATE OR REPLACE TRIGGER TRIGGER2
AFTER INSERT 
ON History
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Site Table After Insert Trigger');
END;
/
@"C:\Users\samsu\OneDrive\Desktop\Project\Site\2.sql"